version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: Install Selenium
          command: npm install selenium-webdriver

  test:
    docker:
      - image: circleci/python:3.7-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Selenium-setup
          command: sudo pip install selenium
      - run:
          name: HelloWorld-test
          command: python test/hello_world_tests.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
