version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-browsers
    steps:
      - checkout
      - - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Selenium
          command: 'sudo npm install selenium-webdriver'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
