version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-browsers
    step:
      - checkout
      - run:
          name: "Install Selenium"
          command: |
            npm install selenium-webdriver

workflows:
  version: 2
  build_and_test:
    jobs:
      -build
