version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.0

executors:
  nodejs:
    docker:
      - image: circleci/node:10.16.3
  python:
    docker:
      - image: circleci/python:3.7-browsers

jobs:
  build:
    executor: nodejs
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install-dependencies
          command: sudo npm install
      - run:
          name: Fix Vulnerabilities
          command: sudo npm audit fix
      - run:
          name: Install Selenium
          command: sudo npm install selenium-webdriver
      - run:
          name: Generate Build
          command: sudo npm run build-dev
      - run:
          name: check-repo
          command: ls

  test:
    docker:
      # Primary container image where all steps run.
      - image: circleci/python:3.7-browsers
      # Secondary container image on common network.
      - image: circleci/node:10.16.3
        command: [sudo npm install]
      - image: circleci/node:10.16.3
        command: [sudo npm run build-dev]
    working_directory: /home/circleci/project
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: check-repo
          command: ls
      - run:
          name: Selenium-setup
          command: sudo pip install selenium
      - run:
          name: HelloWorld-test
          command: python test/hello_world_tests.py
      - run:
          name: Activetab-test
          command: python test/active_tabs_issue\#33.py
      - run:
          name: Tabgroup-test
          command: python test/tab_group_test_issue\#15.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
