version: 2.1
jobs:
  test:
    - image: circleci/python:3.7-browsers
    - run:
        name: "Install Selenium"
        command: npm install selenium-webdriver
    - run:
        name: "Running Selenium Test"
        command: python test/hello_world_tests.py

workflows:
  version: 2
  build_and_test:
    jobs:
      -test
