version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.0

executors:
  nodejs:
    docker:
      - image: circleci/node:10.16.3
  python:
    docker:
      - image: circleci/python:3.7-browsers

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: update-npm
          command: whoami
      - run:
          name: install-dependencies
          command: sudo npm install
      - run:
          name: Install Selenium
          command: sudo npm install selenium-webdriver
      - run:
          name: Generate Build
          command: sudo npm run build-dev
      - run:
          name: Fix Vulnerabilities
          command: sudo npm audit fix

  test:
    executor: python
    working_directory: ～/test
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Selenium-setup
          command: sudo pip install selenium
      - run:
          name: HelloWorld-test
          command: python test/hello_world_tests.py
      - run:
          name: Activetab-test
          command: python test/active_tabs_issue\#33.py
      - run:
          name: Tabgroup-test
          command: python test/tab_group_test_issue\#15.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
